[package]
name = "bilal"
version = "0.1.0"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salah = "0.4.2"
clap = "3.0.0-beta.2"
chrono = "0.4"
indexmap = "1.6.0"
toml = "0.5.6"
