[package]
name = "bilal"
version = "0.2.1"
authors = ["azzamsa <me@azzamsa.com>"]
categories = ["date-and-time", "command-line-utilities"]
edition = "2021"
keywords = ["salah", "pray", "islam"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/azzamsa/bilal"
description = "a CLI salah time"

[profile.release]
opt-level = 'z' # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
islam = "0.2.0"

atty = "0.2"
colored = "2.0"
miette = { version = "5.5.0", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.5"

[dependencies.clap]
version = "4.0.30"
features = ["suggestions", "color", "cargo", "derive"]

[dependencies.time]
version = "0.3"
features = ["formatting", "local-offset"]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
