[package]
name = "bilal"
version = "0.1.1"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salah = { git = "https://github.com/azzamsa/salah", branch = "bilal" }
clap = "3.0.0-beta.2"
indexmap = "1.6.0"
toml = "0.5.6"
colored = "2.0.0"
serde = { version = "1.0.116", features = ["derive"] }

[profile.release]
opt-level = 'z'  # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'
